# Generated by Django 5.2 on 2025-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcribe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="full_name",
        ),
        migrations.AddField(
            model_name="register",
            name="username",
            field=models.CharField(default="gest_user", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
