# Generated by Django 5.2 on 2025-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('link', models.URLField()),
                ('content_embedding', models.BinaryField()),
            ],
        ),
    ]
