# Generated by Django 5.2 on 2025-06-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0004_newsarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone_number',
        ),
    ]
